name: input_quantity
description: A widget for input quntity. Quantity input buult with textfield, type manually or increase/decrease by button
version: 0.0.1
homepage: https://github.com/pmatatias/input-quantity
issue_tracker: https://github.com/pmatatias/input-quantity/issues

environment:
  sdk: ">=2.17.3 <3.3.2"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

 